bubble/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('users/', include('django.contrib.auth.urls')),
    path('', include(('bubbleapp.urls','bubbleapp'),namespace='bubbleapp')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

]

bubbleapp/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^categories/$',views.categories,name='categories'),
    re_path(r'new_category/$',views.new_category,name='new_category'),
    re_path(r'edit_category/(?P<category_id>\d+)/$', views.edit_category,name='edit_category'),
    re_path(r'edit_category/(?P<category_id>\d+)/delete/$', views.delete_category, name='delete_category'),
    re_path(r'^transactions/$',views.transactions,name='transactions'),
    re_path(r'new_transaction/(?P<transaction_id>\d+)/$',views.new_transaction,name='edit_transaction'),
    re_path(r'new_transaction/$',views.new_transaction,name='new_transaction'),
    re_path(r'new_transaction/(?P<transaction_id>\d+)/delete/$', views.delete_transaction, name='delete_transaction'),
    re_path(r'^report_form/$',views.report,name='report_form'),
    re_path(r'^about/$',views.about,name='about'),


]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import login
from . import views

urlpatterns = [
    #Сторінка входу
    url(r'^login/$',login,name='login'),
    #Сторінка виходу
    url(r'^logout/$', views.logout_view, name='logout'),
    #Сторінка реєстрації
    url(r'^register/$', views.register, name='register'),

]

bubbleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=30)
    about=models.CharField(max_length=100)
    user=models.ForeignKey('auth.User',on_delete=models.CASCADE)

    class Meta():
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

#-------------------------
class Subcategory(models.Model):
    subcategory=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    name=models.CharField(max_length=50)
    about = models.CharField(max_length=100)
    class Meta():
        verbose_name_plural = 'subcategories'
    def __str__(self):
            return self.name

#-------------------------
class Transaction(models.Model):
    OPERATION_TYPE_CHOICES=((1,'Витрата'),(2,'Прибуток'))
    trans=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    operation_type=models.DecimalField(
        max_digits=1,
        choices=OPERATION_TYPE_CHOICES,
        default=1,decimal_places=0)
    money=models.DecimalField(max_digits=6,decimal_places=2,default=0.00)
    date=models.DateField()
    about = models.CharField(max_length=100)
    user=models.ForeignKey('auth.User',on_delete=models.CASCADE)

    class Meta():
        verbose_name_plural = 'transactions'

    def name_of_Category(self):
        try:
            name=Category.objects.get(id=self.trans.pk)
        except:
            return 'Відсутня категорія'
        return name.name

    def __str__(self):
            return self.about


    def __add__(self, other):
        if self.operation_type==1:
            return -self.money
        else:
            return self.money

bubbleapp/forms.py
from django import forms
from .models import Category,Transaction
from django.contrib.auth.models import User
import datetime
from bootstrap_datepicker_plus import DatePickerInput

class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=['name','about']
        labels={'name':'Назва','about':'Опис'}


class TransactionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user=kwargs.pop('user')
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields['trans'].queryset=Category.objects.filter(user=user)
        self.fields['date'].widget=DatePickerInput(attrs={'size':'40'})

    class Meta():
        model=Transaction
        fields=['trans','operation_type','money','date','about']
        labels={'trans':'Категорія','operation_type':'Тип операції',
                'money':'Сума','date':'Дата','about':'Опис'}
        # widgets={'date': DatePickerInput(attrs={'size':'40'}),}


class ReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user=kwargs.pop('user')
        super(ReportForm, self).__init__(*args, **kwargs)
        categories=Category.objects.filter(user=user).values('id','name')
        choices = [[0, '']]
        for category in categories:
            choice=[]
            for key in category:
                choice.append(category[key])
            choices.append(choice)
        self.fields['category']=forms.TypedChoiceField(label='Категорія',choices=choices,coerce=int)

    t=Transaction
    date1=forms.DateField(widget=DatePickerInput(), label='Початкова дата',initial=datetime.date.today)
    date2 = forms.DateField(widget=DatePickerInput(),label='Кінцева дата',initial=datetime.date.today)
    operation_type=forms.TypedChoiceField(label='Тип операції',choices=t.OPERATION_TYPE_CHOICES,coerce=int)

bubbleapp/views.py
from django.shortcuts import render
from .models import Category,Subcategory,Transaction
from .forms import CategoryForm,TransactionForm,ReportForm
from django.http import HttpResponseRedirect,HttpResponse,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
# Create your views here.



def index(request):
    #Home page
    context={}
    return render(request,'index.html',context)


@login_required
def categories(request):
    #Page with categories
    # categories=Category.objects.filter(owner=request.user).order_by('name')
    categories = Category.objects.filter(user=request.user).order_by('name')
    context={'categories':categories}
    return render(request, 'categories.html',context)


@login_required
def new_category(request):
    #Adding of new category
    if request.method != 'POST':
        # Дані не відправлялися, створюється нова формв
        form = CategoryForm()
    else:
        # Відправлені дані POST: обробити дані
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_category=form.save(commit=False)
            new_category.user=request.user
            new_category.save()
            return HttpResponseRedirect(reverse('bubbleapp:categories'))
    context = {'form': form}
    return render(request, 'new_category.html', context)


@login_required
def edit_category(request,category_id):
    #Editing existing category
    category = Category.objects.get(id=category_id)
    if category.user != request.user:
        raise Http404

    if request.method != 'POST':
        # Початковий запит. Форма заповнюється наявними даними.
        form = CategoryForm(instance=category)
    elif 'reset' in request.POST:
        form = CategoryForm()
    else:
        # Відправка даних POST. Обробити дані.
        form = CategoryForm(instance=category,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('bubbleapp:categories'))
    context = {'category': category,'form': form}
    return render(request, 'edit_category.html', context)


@login_required
def delete_category(request,category_id):
    # Deleting existing category
    category = Category.objects.get(id=category_id)
    if category.owner != request.user:
        raise Http404
    Category.objects.filter(id=category_id,owner=request.user).delete()
    return HttpResponseRedirect(reverse('bubbleapp:categories'))


@login_required
def transactions(request):
    #Shows transactions
    transactions=Transaction.objects.filter(user=request.user).order_by('-date')
    context={'transactions':transactions}
    return render(request, 'transactions.html',context)


@login_required
def new_transaction(request,transaction_id=0):
    #Adds/changes new transaction
    if transaction_id:
        transaction = Transaction.objects.get(id=transaction_id)
        if transaction.user != request.user:
            raise Http404
        if request.method != 'POST':
            # Початковий запит. Форма заповнюється наявними даними.
            form = TransactionForm(instance=transaction,user=request.user)
        else:
            # Відправка даних POST. Обробити дані.
            form = TransactionForm(instance=transaction, data=request.POST,user=request.user)
            if form.is_valid():
                new_transaction=form.save(commit=False)
                new_transaction.user = request.user
                new_transaction.save()
                return HttpResponseRedirect(reverse('bubbleapp:transactions'))
        context = {'transaction': transaction, 'form': form}
        return render(request, 'new_transaction.html', context)
    else:
        if request.method != 'POST':
            # Дані не відправлялися, створюється нова формв
            form = TransactionForm(user=request.user)
        else:
            # Відправлені дані POST: обробити дані
            form = TransactionForm(request.POST,user=request.user)
            if form.is_valid():
                new_transaction = form.save(commit=False)
                new_transaction.user = request.user
                new_transaction.save()
                return HttpResponseRedirect(reverse('bubbleapp:transactions'))
        context = {'form': form}
        return render(request, 'new_transaction.html', context)


@login_required
def delete_transaction(request,transaction_id):
    # Deleting existing transaction
    transaction = Transaction.objects.get(id=transaction_id)
    if transaction.user != request.user:
        raise Http404
    Transaction.objects.filter(id=transaction_id).delete()
    return HttpResponseRedirect(reverse('bubbleapp:transactions'))


def about(request):
    #Shows page with information about site
    form=ReportForm()
    context={'form':form}
    return render(request,'about.html',context)


@login_required
def report(request):
    #Form with report
    if request.method != 'POST' or ('reset' in request.POST):
        # Дані не відправлялися, створюється нова форма
        form = ReportForm(user=request.user)
    else:
        # Відправлені дані POST: обробити дані
        form = ReportForm(request.POST,user=request.user)
        if form.is_valid():
            context = graph_parameters(request,form.cleaned_data)
            if 'by date' in request.POST:
                return render(request, 'report_line_chart.html', context)
            else: #if 'graph' in request.POST
                return render(request, 'report_pie_chart.html', context)

    context={'form':form}
    return render(request,'report_form.html',context)


def display_meta(request):
    values = request.META.items()
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def graph_parameters(request,params):
    #Takes parameters in request.POST and returns data for Line and Pie Charts
    dates = []
    values_by_day = []
    chart_categories_names=[]
    chart_categories_values=[]
    results=Transaction.objects.filter(user=request.user).filter(date__gte=params['date1'])\
        .filter(date__lte=params['date2'])
    if params['operation_type']:
        results=results.filter(operation_type__exact=params['operation_type'])
    results_by_category = results
    if params['category']:
        results=results.filter(trans__id__exact=params['category'])
    #Makes label for operation type for search
    operation_type=params['operation_type']
    if operation_type==1:
        operation_type='Витрати'
    else:
        operation_type = 'Доходи'
    #Make categories name
    category=params['category']
    if category:
        category=Category.objects.get(id=category).name
    else:
        category='Усі категорії'
    # Make sorted list for all dates:
    for result in results:
        dates.append(str(result.date))
    for res in results_by_category:
        chart_categories_names.append(res.name_of_Category())
    dates=list(set(dates))
    dates.sort()
    chart_categories_names=list(set(chart_categories_names))
    chart_categories_names.sort()
    # Make period
    period = str(params['date1']) + '  --  ' + str(params['date2'])
    #Make Sum for all dates:
    for date in dates:
        sum=results.filter(date__exact=date).aggregate(Sum('money'))['money__sum']
        values_by_day.append(str(int(sum*100)/100))
    for cat in chart_categories_names:
        sum = results_by_category.filter(trans__name__exact=cat).aggregate(Sum('money'))['money__sum']
        chart_categories_values.append(str(int(sum*100)/100))
    #SELECT category.name, sum(money) FROM results group by category.name
    sum_by_categories=results_by_category.values('trans__name').annotate(Sum('money'))
    sum=results_by_category.values('trans__name').aggregate(money=Sum('money'))
    # Making string with values for convertion in chart script:
    dates = ' '.join(dates)
    values_by_day = ' '.join(values_by_day)
    chart_categories_names=' '.join(chart_categories_names)
    chart_categories_values=' '.join(chart_categories_values)
    #At least:... =)
    context={'dates':dates,'values_by_day':values_by_day,'operation_type1':operation_type,'period':period,
             'category':category,'chart_categories_names':chart_categories_names,'sum':sum,
             'chart_categories_values':chart_categories_values,'sum_by_categories':sum_by_categories}
    return context

bubbleapp/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>About this project</h1><br>
<p>This project was created in learning purposes by 
<a href="https://github.com/Yarema-Kryven" title="GitHub account">Yarema Kryven</a>.</p>
<p>For contacts please e-mail me to 
<a href = "mailto: brebeneskyl@gmail.com">brebeneskyl@gmail.com</a></p>
{% endblock content %}

bubbleapp/templates/base.html
<!DOCTYPE html>
<html lang="ua">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>

<body style="height:1500px">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <!-- Brand -->
  <a class="navbar-brand" href="/">BUBBLE</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'bubbleapp:categories' %}">Categories</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="/" id="navbardrop" data-toggle="dropdown"> Actions</a>
         <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'bubbleapp:transactions' %}">Transactions</a>
           <a class="dropdown-item" href="{% url 'bubbleapp:report_form' %}">Report</a>
         </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'bubbleapp:about' %}">Help</a>
    </li>
    <li class="nav-item">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/" id="navbardrop" data-toggle="dropdown"> Hello, {{ user.username }}</a>
            <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
            </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">LogIn</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}">register</a>
        </li>
        {% endif %}
    </li>
  </ul>
</nav>

<div class="container-fluid" style="margin-top:80px">
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</div>
</body>
</html>

bubbleapp/templates/categories.html
{% extends "base.html" %}
{% block content %}
<h1>Категорії витрат/доходів</h1><br>
<div class="jumbotron jumbotron-fluid">
  <div class="container">

  <table class="table table-hover table-striped table-bordered table-sm">
    <thead class="thead-light">
      <tr>
        <th>#</th>
        <th>Назва</th>
        <th>Опис</th>
        <th>Управління</th>
      </tr>
    </thead>
    <tbody>
    {% for category in categories %}
      <tr>
        <td>{{ category.id }}</td>
        <td>{{ category }}</td>
        <td>{{ category.about }}</td>
        <td><a class="btn btn-primary btn-outline-dark btn-light btn-sm"
               href="{% url 'bubbleapp:edit_category' category.id %}" role="button">C</a>

            <a class="btn btn-primary btn-outline-dark btn-light btn-sm"
            role="button" onclick=questionFunction()>D</a></td>
          <script type="text/javascript">
              function questionFunction(){
                  var answer= confirm('ВИ ВПЕВНЕНІ ЩО ХОЧЕТЕ ВИДАЛИТИ ЦЮ КАТЕГОРІЮ?\nТранзакції здійснені по цій' +
                  ' категорії залишаться, проте будуть позначені як \'Без Категорії\'. Якщо ви не знатимете' +
                  ' що далі із ними робити, то люди ненавидітимуть вас, а сім’я та друзі зневажатимуть.');
              if (answer) {deletingFunction()}
              else {hahaFunction()}
              }

            function deletingFunction() {
                var person = prompt("For deleting type 'DELETE'", "");
                if (person == 'DELETE') {
                window.location.href = '{% url 'bubbleapp:delete_category' category.id %}'
                }
                else if (person!=null) {alert('Ти ввів щось не те що тебе просили для видалення цієї категорії.' +
                    ' Спробуй ще раз.')
                }
            }

            function hahaFunction() {
                alert('Ага! Злякався!\n Молодець...  =)')
            }
          </script>

      </tr>
    {% endfor %}
    </tbody>
  </table>
  <button onclick="goNewCat()">Додати нову категорію</button>
  <button onclick="goTrans()">Транзакції</button>
  <script>
      function goNewCat() {window.location.href={% url 'bubbleapp:new_category' %}}
      function goTrans() {window.location.href={% url 'bubbleapp:transactions' %}}
  </script>
  </div>
</div>
{% endblock content %}

bubbleapp/templates/edit_category.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
    <p>Edit entry:</p>
    <form action="{% url 'bubbleapp:edit_category' category.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Зберегти</button>
        <button name="reset" >Очистити</button>
        <button name="cansel" onclick=goBack()>Відміна</button>
        <script>
            function goBack() {window.location.href={%url 'bubbleapp:categories' %};}
        </script>
    </form>

    </div>

{% endblock content %}

bubbleapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome!</h1><br>
<p>With this application you can calculate your expenses and revenues.</p>
<p>To learn more, find activities in navigation bar.</p>
{% endblock content %}

bubbleapp/templates/new_category.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron jumbotron-fluid">
    <h1>Додати нову категорію:</h1>
    <form action="{% url 'bubbleapp:new_category' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button style="float: left;margin-right: 10px;margin-left: 10px"  name="submit">Додати категорію</button>
    </form>
  <button onclick=goCat()>Категорії</button>
  <script>
      function goCat() {window.location.href='{% url 'bubbleapp:categories' %}'}
  </script>
  </div>
{% endblock content %}

bubbleapp/templates/new_transaction.html
{% extends "base.html" %}
{% block content %}
        {% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
    {{ form.media }}
<h1>Додати нову транзакцію:</h1>
    <div class="jumbotron jumbotron-fluid" style="margin: 50px">
  <div class="row">
    <div class="col-8">
  {% if transaction.id %}
    <form action="{% url 'bubbleapp:edit_transaction' transaction.id %}" method='post'>
  {% else %}
    <form action="{% url 'bubbleapp:new_transaction' %}" method='post'>
  {% endif %}
        {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}

  {% if transaction.id %}
    <button style="float: left;margin-right: 10px;margin-left: 10px" name="submit">Змінити транзакцію</button>
  {% else %}
    <button style="float: left;margin-right: 10px;margin-left: 10px" name="submit">Додати транзакцію</button>
  {% endif %}
    </form>
  <button onclick=goTrans()>Транзакції</button>
  <script>
      function goTrans() {window.location.href='{% url 'bubbleapp:transactions' %}'}
  </script>
  </div>
  </div>
    </div>
{% endblock content %}

bubbleapp/templates/report_form.html
{% extends "base.html" %}
{% block content %}
    {% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
    {{ form.media }}
    <h1>Генератор звітів:</h1>
  <div class="jumbotron jumbotron-fluid">
  <div class="col-sm-6">
    <form action="{% url 'bubbleapp:report_form' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

    <button style="margin-left: 10px" name="by date">По датах</button>
    <button name="graph">Графік</button>
    <button name="reset">Очистити</button>
    </form>
   </div>
  <button style="margin: 10px" onclick=goTrans()>Транзакції</button>

  </div>
    <script>
    function goTrans() {window.location.href='{% url 'bubbleapp:transactions' %}'}
    </script>
{% endblock content %}

bubbleapp/templates/report_line_chart.html
{% extends "base.html" %}
{% block content %}
<h1>Звіт по днях</h1><br>
<p>Категорія: {{ category }}</p>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">

var t1 = "{{ period }}";
var t2 = "{{ dates }}";
var t3 = "{{ operation_type1 }}";
var t4 = "{{ values_by_day }}";
var t5 = "{{ operation_type2 }}";
var t6 = "{{ values2 }}";

var tagList1 = t4.split(' ');
moneyList1=[];
tagList1.forEach(function(item, i, arr)
{
    moneyList1.push(Number(item));
});
var datesList=t2.split(' ');



Highcharts.chart('container', {
  chart: {
    type: 'line'
  },
  title: {
    text: 'Звіт за період:'
  },
  subtitle: {
    text: t1
  },
  xAxis: {
    categories: datesList
  },
  yAxis: {
    title: {
      text: 'UAH'
    }
  },
  plotOptions: {
    line: {
      dataLabels: {
        enabled: true
      },
      enableMouseTracking: false
    }
  },
  series: [{
    name: t3,
    data: moneyList1
  }]
});
</script>
{% endblock content %}

bubbleapp/templates/report_pie_chart.html
{% extends "base.html" %}
{% block content %}
<h1>Звіт по категоріях</h1><br>
<h2>Період: {{ period }}</h2>
<hr>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>


<div id="container1" style="width: 30%; float: left;padding: 20px;background-color: ghostwhite">
  <table class="table table-hover table-striped table-bordered table-sm">
    <thead class="thead-light">
      <tr>
        <th>Категорія</th>
        <th>Сума</th>
      </tr>
    </thead>
    <tbody>
    {% for category in sum_by_categories %}
      <tr>
        <td>{{ category.trans__name }}</td>
        <td>{{ category.money__sum|floatformat:2 }}</td>
      </tr>
    {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <th style="text-align: center;font-weight: bold;font-style: italic">Всього:</th>
        <th> {{ sum.money|floatformat:2 }} </th>
      </tr>
    </tfoot>
  </table>
  </div>

<div id="container" style="width: 30%; margin: 0; float: left">
<script type="text/javascript">
/*context={'dates':dates,'values_by_day':values_by_day,'operation_type1':operation_type,'period':period,
             'category':category,'chart_categories_names':chart_categories_names,
             'chart_categories_values':chart_categories_values}*/
var t1 = "{{ operation_type1 }}";
var t2 = "{{ chart_categories_names }}";
var t3 = "{{ chart_categories_values }}";

var namesList = t2.split(' ');
var valuesList=t3.split(' ');
objectsList=[];
var i;
for (i=0;i<namesList.length; i++)
{
    object={name:namesList[i], y:Number(valuesList[i])};
    objectsList.push(object);
}



Highcharts.chart('container', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: t1
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                style: {
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                }
            }
        }
    },
    series: [{
        name: 'частка',
        colorByPoint: true,
        data: objectsList
    }]
});
</script>
</div>
{% endblock content %}

bubbleapp/templates/transactions.html
{% extends "base.html" %}
{% block content %}
<h1>Транзакції</h1><br>
<div class="jumbotron jumbotron-fluid" style="padding: 1rem">
  <div class="container">
  <button onclick="goNewTrans()">Додати нову транзакцію</button>
  <button onclick="goReportForm()">Генератор звітів</button>
  <button onclick="goCat()">Категорії</button>
  <script>
      function goNewTrans() {window.location.href='{% url 'bubbleapp:new_transaction' %}'}
      function goReportForm() {window.location.href='{% url 'bubbleapp:report_form' %}'}
      function goCat() {window.location.href='{% url 'bubbleapp:categories' %}'}
  </script>
  <table class="table table-hover table-striped table-bordered table-sm">
    <thead class="thead-light">
      <tr>
        <th>#</th>
        <th>Категорія</th>
        <th>Тип операції</th>
        <th>Сума</th>
	    <th>Дата</th>
	    <th>Опис</th>
	    <th>Управління</th>
      </tr>
    </thead>
    <tbody>
    {% for transaction in transactions %}
      <tr>
        <td>{{ transaction.id }}</td>
        <td>{{ transaction.name_of_Category }}</td>
        <td>{{ transaction.get_operation_type_display }}</td>
        <td>{{ transaction.money }}</td>
        <td>{{ transaction.date|date:'Y-m-d' }}</td>
        <td>{{ transaction.about }}</td>
        <td><a class="btn btn-primary btn-outline-dark btn-light btn-sm"
               href="{% url 'bubbleapp:edit_transaction' transaction.id %}" role="button">C</a>
        <a class="btn btn-primary btn-outline-dark btn-light btn-sm"
            role="button" onclick=questionFunction()>D</a></td>
          <script type="text/javascript">
              function questionFunction(){
                  var answer= confirm('ВИ ВПЕВНЕНІ ЩО ХОЧЕТЕ ВИДАЛИТИ ЦЮ ТРАНЗАКЦІЮ?');
              if (answer) {deletingFunction()}}

            function deletingFunction() {
                var person = prompt("For deleting type 'DELETE'", "");
                if (person == 'DELETE') {
                window.location.href = '{% url 'bubbleapp:delete_transaction' transaction.id %}'
                }
                else if (person!=null) {alert('Ти ввів щось не те що було потрібно для видалення цієї транзакції.' +
                    ' Спробуй ще раз.')
                }
            }
          </script>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock content %}